apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "hub-spoke-sno"
  namespace: "hub-spoke-sno"
spec:
  baseDomain: "karmalabs.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk/okmLQtSrTkhZEpavacdFSSnkA+0e0A3Dn1qs7QSJA2oy+3cCtsUcCcX+wU122TRNFwE2j6V3iS1tHMVjps2HW9CI7U2lfBCba8I1MwRqXcETbWEynHic+SXTDIyJ19G3wDYWAe3aZ7+8jsAbNNpyhLIsaeVPpaHjyRzzOw37jvdUPCzqJAMOZB8XaoMcI46RXveb1LWuLjRl6iIUvAqk9BQ2gXoYV81W2HipAhjfvlmdAg5fW9D84oN/peQTSgGA+y4VCrIMqeAkZmQ8ku07H2OAEVWkacXulZz8m/l0cEO1wC/uwc/z50xjUIYy0d0GNn0ffcYOIQwbYqjqbRPkz8KRmiT9LImTqnSiV5AuUb/tkxH7MZzQrdv2ATAIiUu+Me58DE2HIGi+N8jCO8OlmtET7e1k9fCZV0NTcRUCw7KF40G0q+m4eoC3j2FBcIT9oD/zYX6SiWSAhNWwDPRWYFbqh4DS/m43mMwOn0QYHrlJLz2CntEMXeRyVIAgw0= root@cnfde19.ptp.lab.eng.bos.redhat.com"
  clusters:
  - clusterName: "hub-spoke-sno"
    networkType: "OVNKubernetes"
    clusterLabels:
      common-410: true
      group-du-sno: ""
      sites : "hub-spoke-sno"
      vendor: "OpenShift"
    clusterNetwork:
      - cidr: 172.16.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.122.0/24
    serviceNetwork:
      - 10.10.0.0/16
    additionalNTPSources:
      - clock.corp.redhat.com
    nodes:
      - hostName: "hub-spoke-sno.karmalabs.com"
        role: "master"
        bmcAddress: "redfish-virtualmedia+http://sushy-openshift-infra.apps.hub.karmalabs.com/redfish/v1/Systems/11111111-1111-1111-1111-111111111191"
        bmcCredentialsName:
          name: "spoke-bmc-secret"
        bootMACAddress: "aa:aa:aa:cc:cc:01"
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
        cpuset: "0-1,6-7"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "aa:aa:aa:cc:cc:01"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                macAddress: "aa:aa:aa:cc:cc:01"
                ipv4:
                  enabled: true
                  address:
                    - ip: 192.168.122.30
                      prefix-length: 24
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - karmalabs.com
                server:
                - 192.168.122.253
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.122.1
                table-id: 254
